<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>apli_website_rebuild</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

  <Target Name="CopySharedFooterToPublishDirectory" AfterTargets="Publish">
    <MakeDir Directories="$(PublishDir)Pages\Shared" />
    <Copy SourceFiles="$(MSBuildProjectDirectory)\Pages\Shared\_Footer.cshtml"
          DestinationFiles="$(PublishDir)Pages\Shared\_Footer.cshtml" />
  </Target>

</Project>
